[package]
name = "benchmark-io-rust"
version = "0.1.0"
authors = ["Yuichi Tanikawa <kojole.jp@gmail.com>"]

[dependencies]
chrono = "0.4"
docopt = "0.8"
libc = "0.2"
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"

[features]
no_each_elapsed_log = []
